periodics:
  - name: test-hypershift-deployment
    interval: 20h
    agent: kubernetes
    spec:
      containers:
        - name: deploy-hypershift
          image: quay.io/powercloud/inbound-agent:4.10-3.2
          envFrom:
            - configMapRef:
                name: hyp-env
          command:
            - /bin/bash
          args:
            - -c
            - |
              echo "Welcome to hypershift e2e"
              mkdir ${DUMP_DIR}
              cd /root
              git clone https://github.com/ppc64le-cloud/hypershift-hacks
              set +x $PULL_SECRET
              export RELEASE_IMAGE=$(curl https://multi.ocp.releases.ci.openshift.org/api/v1/releasestream/4.12.0-0.nightly-multi/latest | jq ".pullSpec" | tr -d '"')
              mkdir ${DUMP_DIR}
              curl https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz -o oc.tar.gz
              tar xzf oc.tar.gz
              mv oc /usr/local/bin/
              mv kubectl /usr/local/bin/
              ibmcloud update -f
              ibmcloud plugin update --all
              apt update -y
              apt install unzip -y
              curl https://dl.google.com/go/go"${GO_VERSION}".linux-amd64.tar.gz -o go"${GO_VERSION}".linux-amd64.tar.gz
              tar -C /usr/local -xzf go"${GO_VERSION}".linux-amd64.tar.gz
              mkdir ~/.docker
              cat pull-secret > ~/.docker/config.json
              nerdctl pull ${RELEASE_IMAGE}
              export PATH=$PATH:/usr/local/go/bin
              cd /root/hypershift-hacks/jenkins
              python3 e2e.py
              if [ $? -ne 0 ]; then
                 echo "hypershift E2e failed" && exit 1
              fi
          env:
          - name: IBMCLOUD_API_KEY
            valueFrom:
              secretKeyRef:
                name: api-key
                key: value
          volumeMounts:
          - name: pull-secret
            mountPath: /var/hypershift-secret
            readOnly: true
      volumes:
      - name: pull-secret
        secret:
          secretName: pull-secret